[package]
name = "crude-profiler"
version = "0.1.7"
authors = ["David Roundy <roundyd@physics.oregonstate.edu>"]
description = "simple library for crude manual profiling"
license = "GPL-2.0+"

[dependencies]

lazy_static = "^0.2.8"
